apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  local:
    push: false # Do not push images to docker hub upon building them
  # googleCloudBuild: # Use google cloud build when pushing changes
  #   projectId: *GCP ID*
  artifacts:
    - image: mathiasbergqvist/auth # ...or id from project in Google Cloud, now it's the local image
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: # What to do when a file changes
        manual:
          - src: "src/**/*.ts" # Sync all ts files inside a scr directory
            dest: . # Where to sync the files to in a running container
    - image: mathiasbergqvist/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
